### PR TITLE
Add `applications` key into `manifest.json` for proper Firefox support

### PR DESCRIPTION
**Pull request by ExE-Boss**
# ⚠️ Moved to #129

This extension uses APIs which are only available in Firefox 55+, and as such the `strict_min_version` has been set to `55.0`. See my comment on [#118](https://github.com/sindresorhus/notifier-for-github-chrome/issues/118#issuecomment-303750401) for details.

### CODE REVIEW

**Comment by benrondeau** [comment]
@sindresorhus Are you accepting pull requests?

**Comment by sindresorhus** [comment]
I'm not really interested in adding extra stuff for Firefox. The whole point of it supporting the Chrome extension API is that it should just work. I'm ok with https://github.com/sindresorhus/notifier-for-github-chrome/pull/128/commits/1f03dc577dc21fdb78bc4809f64fc94b58d81885 if you do a separate PR for it.

**Comment by ExE-Boss** [comment]
@sindresorhus In that case, we have to wait for Firefox 55, which will add the [`permissions`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/permissions) API.

**Comment by ExE-Boss** [comment]
PR moved to #129

**Pull request closed without merging**
